[package]
name = "miri-the-world"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
crates_io_api = "0.8.0"
env_logger = "0.9.0"
log = "0.4.16"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
ansi-to-html = { git = "https://github.com/Aloso/to-html", features = ["once_cell"] }

[profile.release]
panic = "abort"
debug = 1
