[package]
name = "miri-the-world"
version = "0.1.0"
edition = "2021"
default-run = "miri-the-world"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.16"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
ansi-to-html = { path = "ansi-to-html", features = ["once_cell"] }
color-eyre = "0.6.1"
rayon = "1.5.1"
ring = "0.16"
hex = "0.4.3"
semver = "1.0.7"
backoff = "0.4.0"
tar = "0.4.38"
flate2 = "1.0.23"
lazy_static = "1.4.0"
ureq = "2.4.0"
tempfile = "3.3.0"
once_cell = "1.10.0"
csv = "1.1.6"
fxhash = "0.2.1"
indicatif = "0.16.2"
regex = "1.5.5"

[profile.release]
debug = 1
